### ISSUE TITLE
Getting error message in command line when running dotnet ef enable

### ISSUE THREAD

**Issue by Ksyruz** [mrahhal/Migrator.EF6#10]
![image](https://cloud.githubusercontent.com/assets/4070672/15931988/dd968f9e-2e51-11e6-8408-18e95f393e2c.png)

**Comment by mrahhal** [comment]
Could you provide more details please? How is your `project.json` structured? You could be missing something.

**Comment by Ksyruz** [comment]
Hi,

"Contexts" is a class library (repository) and the "Web" is the webapi.

I am running the commands using the class library location with the connection string embedded into the code.

**Comment by mrahhal** [comment]
See #9.
Currently with "Tools Preview 1" you can't use a .NET Core tool in a library project.

What you can do is have the "Contexts" project contain your models, that's fine. But you'll have to use migrations inside your web app. So you'll use `dotnet ef` inside your webapi project instead of your "Contexts" project.

**Comment by Ksyruz** [comment]
Thanks for getting back so fast, I will do that.

**Comment by mrahhal** [comment]
@Ksyruz I'm closing this. If you still have problems you can open a new one.
