### ISSUE TITLE
Specifying a target Migrations directory.

### ISSUE THREAD

**Issue by AlonCG** [mrahhal/Migrator.EF6#24]
Is it possible to specify a target Migrations directory? 

Currently ... even when my configuration lists a non-default ("Data\Migrations") folder, the migrations are still added to the default "Migrations" folder. 

I see in your "Executor" that the folder appears hard-coded, any way to add a switch to enable another location? It is not overly critical, as I can just move the migrations, but it would be nice.

Thanks for all your work and assistance.

**Comment by mrahhal** [comment]
When I started working on this I just enabled what is mostly critical for apps to work and just went with it. So yeah there are a couple of hard coded stuff. I planed on enabling more features in the underlying migrator but I just didn't see an actual necessity.

But It has been a while since I did a review on this so I guess I should do a couple of those little wanted features and do an update. Keep this open and I'll let you know when I update.

**Comment by AlonCG** [comment]
Awesome thanks!

**Comment by mrahhal** [comment]
Okay, so. You'll have to specify your migrations dir in both the `enable` and the `add` command.

So:

```
dotnet ef migrations enable -o Foo
dotnet ef migrations add MigrationName -o Foo
```

**Comment by AlonCG** [comment]
Yes ... that seems like the MS implementation (according to their docs).

**Comment by mrahhal** [comment]
I'll let you know when I do a package update. (probably very soon)

**Comment by AlonCG** [comment]
Killer, thanks!

**Comment by mrahhal** [comment]
@AlonCG `1.0.1`

**Comment by AlonCG** [comment]
Awesome! Thanks again and could not have even dreamed of a better response time! I will try it out in a few minutes.

**Comment by mrahhal** [comment]
Haha don't worry about it. Glad to help.

**Comment by AlonCG** [comment]
Thanks again ... "-o" working so far!
