### ISSUE TITLE
Can't get migrations to work

### ISSUE THREAD

**Issue by findulov** [mrahhal/Migrator.EF6#5]
Hi, I'm having DAL package class library for my database operations and I've targeted it only with .NET 4.5.1 version (dnxcore50 reference is removed) and I've decided to use Entity Framework 6. I have added your MigratorEF6 assembly to my project and I have referenced it in my DAL. But when I try to use **dxn ef** command, an error occurs saying:

![xxxx](https://cloud.githubusercontent.com/assets/5251112/14768090/4604b028-0a40-11e6-859c-dacf61e6049e.PNG)

I think I'm not doing something right, but that's the way I've used to do it with EF7 initially before I give up on it.

**Comment by joshiji** [comment]
Your DNX version is using CoreClr. You can list the run time using `dnvm list`. This will show that active DNX runtime.

You may want to change it from command line. The command to change it should be 
`dnvm use 1.0.0-rc1-update1 -r clr`

You can verify it using `dnvm list`. If it still doesn't work, you may try setting the `default` alias to the active CLR version of runtime. Let us know how does it go.

**Comment by mrahhal** [comment]
As @santoshkumarjoshi said make sure you're running the full .net framework instead of coreclr.

Another note: I didn't try, but I think the migrator currently won't work if your migrations are not in your app or web app (for example in your `DAL` project that you reference from your app) so check that as well because I see you're doing `dnx ef` in your `DAL` project. I might add support for this if it's being needed by people.

**Comment by findulov** [comment]
Thank you, @santoshkumarjoshi, changing to the `clr` instead of `CoreClr` worked!
@mrahhal, I'd like to let you know that `dnx ef` command works for my `DAL` project.

**Comment by mrahhal** [comment]
@ge6a93 nice, good to know.
