### ISSUE TITLE
Your startup project doesn't reference Microsoft.EntityFrameworkCore.Design

### ISSUE THREAD

**Issue by DOTang** [mrahhal/Migrator.EF6#61]
Hi, long time user of your add on, but I seem to have an issue now. I am using 1.1.4 because I am using 1.x of CORE. I have an MVC project in the solution, and my DbContext/Entities in a separate class library.

In the class library csproj I have:
```
<ItemGroup>
    <PackageReference Include="AutoMapper" Version="6.2.2" />
    <PackageReference Include="AutoMapper.EF6" Version="1.1.1" />
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="1.1.2" />
    <PackageReference Include="Migrator.EF6.Tools" Version="1.1.4" PrivateAssets="All" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.0.8.2" />
  </ItemGroup>
  
  <ItemGroup>
	<DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.1.4" />
  </ItemGroup>
```
I open Developer Command Prompt, cd to my class library directory and try dotnet ef migrations add:

> C:\Users\me\Documents\Visual Studio 2015\Projects\MySolution\src\MyClassLibrary>dotnet ef migrations add AddedSomething

and it spits out:

> Your startup project doesn't reference Microsoft.EntityFrameworkCore.Design. This package is required for Entity Framework Core Tools to work. Ensure your startup project is correct, install the package, and try again.

It's been about a month since I last needed to run a migration, but I did it how I always did it with your library. Now it doesn't work. Something changed I guess, but what? Why does it seem like it is trying to use the default EF tooling now?

These are my references in the class library project:
![image](https://user-images.githubusercontent.com/3045507/45841519-b0847600-bcdf-11e8-91df-093a99588cd3.png)

And my context class in class library looks like this:
```
public MyContext() : base(MyStaticApi.GetConnectionStringName())
        {
            Database.SetInitializer<MyContext>(null);
            Database.Log = Console.Write;
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
            Configuration.AutoDetectChangesEnabled = false;
        }
```
Nothing has changed so I don't know what's going on. Can you please help? Thanks.

**Comment by mrahhal** [comment]
Hi there,

Starting from netcore sdk 2.0, the dotnet ef core tool is included in the vanilla `dotnet` tool. So, `dotnet ef` starts referring to the dotnet ef core tool regardless of whether you have my tool installed.

In the later versions, I changed my tool name to be `dotnet ef6`. But in your case, you'll need to create a "global.json" file to change the dotnet sdk you want to use. Since you're using 1.x, you'll want to target a version before 2.0 sdk.

Docs on global.json can be viewed here: https://docs.microsoft.com/en-us/dotnet/core/tools/global-json

**Comment by DOTang** [comment]
Oh wow, great thanks for that. I put into my class library yes? When I did that great, now it looks like it's trying to reference your tools again, but it says:

> Version for Package `Migrator.EF6.Tools` could not be resolved.

I check the .csproj and both 1.1.4 are referenced. I tried referencing SDK versions 1.1.7 and 1.1.0 in the global.json (making sure they are both installed), and both have same error. Also tried version 1.1.3 of your tools, also same error.

**Comment by DOTang** [comment]
Nevermind I figured it out, had to just rerun dotnet restore. Now it works again! Thank you for your help and wonderful library helped me all these years before MS catches up!

**Comment by mrahhal** [comment]
Glad to help!

**Comment by alpersilistre** [comment]
Hi, I am having the same issue in my project. This project was migrated from VS2015 to VS2017, Visual Studio changed project files from xproj to csproj, remove project.json files inside all projects in the solution and we continued to work on it. Now, we just realized we can't add or run any migrations. We used to run it in VS2015. 

It gives '**Your startup project 'App.EntityFramework' doesn't reference Microsoft.EntityFrameworkCore.Design...**' error.

We were using Migrator.EF6 tools to handle EF migrations in an Asp Net Core 1.x project. I followed @mrahhal suggestion about adding project.json file to the class library project where our DB Context and migrations reside but unfortunately, I am still getting the same error. I guess Visual Studio still trying to run EF Core migrations and that's the reason it gives this error.

The version of the Migrator.EF6 package is 1.0.8. I tried several updated versions of it but it doesn't solve the issue.

This is the csproj file of the project;
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.0.0</VersionPrefix>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>Mc.App.EntityFramework</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>Mc.App.EntityFramework</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mc.App.Core\Mc.App.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Migrator.EF6.Tools" Version="1.0.8" />
    <PackageReference Include="Abp.Zero.EntityFramework" Version="1.2.0" />
    <PackageReference Include="Abp.EntityFramework" Version="1.2.2" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Migrator.EF6.Tools" Version="1.0.8" />
  </ItemGroup>

</Project>
```

This is the project.json file I added back. This is the same as our old(VS2015) project.json file except net461 is changed with net472 since we updated all projects to work with .NET Framework 4.7.2.
```
{
  "version": "1.0.0.0-*",

  "dependencies": {
    "Mc.App.Core": "1.0.0.0-*",
    "Migrator.EF6.Tools": "1.0.8",
    "Abp.Zero.EntityFramework": "1.2.0",
    "Abp.EntityFramework": "1.2.2"
  },

  "tools": {
    "Migrator.EF6.Tools": {
      "version": "1.0.8",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "buildOptions": {
    "emitEntryPoint": true
  },

  "frameworks": {
    "net472": {
      "Microsoft.NETCore.App": "1.0.0-rc2-3002702"
    }
  }
}
```

I also tried this version of the project.json file (**just included SDK version as its shown in the Microsoft link to force it to use 1.x**) but it also doesn't change anything.
```
{
  "sdk": {
    "version": "1.0.0.0-*" (Also tried several other version here)
  }
}
```

I would be glad to hear any suggestions or help. Thanks.

**Comment by mrahhal** [comment]
Hi @alpersilistre 

Can you please open a new issue for this? But before that, maybe try to run the sample app that comes with this repository, just to know if the problem is in your project or the environment.
